public class EclipseWarmUp {
	public EclipseWarmUp() {
		set();
		print();
	}

	public static void main(String[] args) {
		new EclipseWarmUp();
	}

	private void print() {
		System.out.print(getPnmpunm());
		System.out.print((char) getEwjevks());
		System.out.print(getZjjag());
		System.out.print((char) getUmoki());
		System.out.print(getWuwibie());
		System.out.print(getXqdwdg());
		System.out.print((char) getJjyvon());
		System.out.print(getKwzh());
		System.out.print(getNddgs());
		System.out.print(getIyogpx());
		System.out.print((char) getEdtugo());
		System.out.print((char) getUuzhq());
		System.out.print(getDlwb());
		System.out.print(getQhds());
		System.out.print((char) getWalxxz());
		System.out.print(getScinylp());
		System.out.print(getMij());
		System.out.print((char) getZwlsist());
		System.out.print(getQxacpne());
		System.out.print((char) getCpf());
		System.out.print((char) getNgyfc());
		System.out.print(getOmpefy());
		System.out.print(getPgjwz());
		System.out.print(getAnqas());
		System.out.print((char) getAqrf());
		System.out.print(getKfz());
		System.out.print(getDowi());
		System.out.print(getBeqyn());
		System.out.print((char) getJgcmo());
		System.out.print(getCua());
		System.out.print(getCjl());
		System.out.print(getJarvuxd());
		System.out.print(getKzbldk());
		System.out.print(getArobm());
		System.out.print(getOwlt());
		System.out.print((char) getVtnhtan());
		System.out.print(getCyjzpx());
		System.out.print(getWpnaokk());
		System.out.print(getOrmctb());
		System.out.print((char) getBunnx());
		System.out.print(getGnigv());
		System.out.print(getVjvlz());
		System.out.print(getDhfj());
		System.out.print((char) getXaqq());
		System.out.print((char) getCbililv());
		System.out.print(getHasc());
		System.out.print(getWsr());
		System.out.print(getPpijfvs());
		System.out.print((char) getIoocj());
		System.out.print((char) getIya());
		System.out.print(getQodrweo());
		System.out.print(getZipzga());
		System.out.print(getTfr());
		System.out.print((char) getGbtijos());
		System.out.print(getAfpdhe());
		System.out.print(getLileqj());
		System.out.print(getEmelqya());
		System.out.print(getThs());
		System.out.print(getQjrvip());
		System.out.print(getYrp());
		System.out.print(getAolxpal());
		System.out.print(getHgtjnfj());
		System.out.print((char) getGfj());
		System.out.print((char) getLpgj());
		System.out.print(getLkqrh());
		System.out.print((char) getPvg());
		System.out.print((char) getQnsf());
		System.out.print((char) getUtdquob());
		System.out.print((char) getKvyjhuh());
		System.out.print(getSoqri());
		System.out.print(getXlahlar());
		System.out.print(getTucxhh());
		System.out.print((char) getRnn());
		System.out.print(getRovwopz());
		System.out.print(getVke());
		System.out.print(getPno());
		System.out.print((char) getWky());
		System.out.print((char) getLtoxdz());
		System.out.print((char) getPoz());
		System.out.print(getPmmfl());
		System.out.print(getWbfajfn());
		System.out.print((char) getBkus());
		System.out.print(getLxfn());
		System.out.print(getNfo());
		System.out.print((char) getJbkqa());
		System.out.print(getGzu());
		System.out.print(getOwxhn());
		System.out.print((char) getRiklilh());
		System.out.print((char) getAtm());
		System.out.print(getGyznywk());
		System.out.print((char) getJea());
		System.out.print((char) getIuhxktq());
		System.out.print(getBqounh());
		System.out.print(getFox());
		System.out.print(getYgbcck());
		System.out.print(getIxfr());
		System.out.print((char) getNdkpjbn());
		System.out.print(getOmzs());
		System.out.print((char) getHbac());
		System.out.print((char) getOcfifg());
		System.out.print(getPxty());
		System.out.print((char) getZmspifu());
		System.out.print((char) getJqnd());
		System.out.print(getMomcef());
		System.out.print((char) getZdn());
		System.out.print((char) getCvtddim());
		System.out.print(getKqaq());
		System.out.print(getBduanf());
		System.out.print(getKmrkc());
		System.out.print((char) getJtaqm());
		System.out.print(getSzfcxq());
		System.out.print((char) getAdhx());
		System.out.print((char) getFhuk());
		System.out.print((char) getNivqumq());
		System.out.print(getMdh());
		System.out.print(getDnjc());
		System.out.print((char) getVmkyv());
		System.out.print(getLhjxtbb());
		System.out.print(getSqb());
		System.out.print((char) getDst());
		System.out.print(getGqj());
		System.out.print(getDfu());
		System.out.print((char) getLnstq());
		System.out.print(getUfax());
		System.out.print(getQlejrpb());
		System.out.print(getEprrnfy());
		System.out.print(getToh());
		System.out.print(getXcqkxd());
		System.out.print(getCiefn());
		System.out.print((char) getYhhklch());
		System.out.print(getFun());
		System.out.print((char) getSwq());
		System.out.print((char) getUznm());
		System.out.print((char) getDshkwx());
		System.out.print(getNcsbxv());
		System.out.print(getOnull());
		System.out.print(getIzk());
		System.out.print(getZrkhllh());
		System.out.print((char) getHbibpn());
		System.out.print(getNba());
		System.out.print(getBzgx());
		System.out.print(getLkzg());
		System.out.print(getKqdevv());
		System.out.print(getLnwm());
		System.out.print((char) getCubs());
		System.out.print(getZgkvkwc());
		System.out.print((char) getWmvyyd());
		System.out.print((char) getYwtp());
		System.out.print(getVajcgb());
		System.out.print((char) getWzxcqy());
		System.out.print(getCehyni());
		System.out.print(getMhsyar());
		System.out.print(getHzbtjm());
		System.out.print(getYkrvop());
		System.out.print(getTalu());
		System.out.print((char) getSycao());
		System.out.print(getQgvxa());
		System.out.print((char) getThic());
		System.out.print((char) getRpkacz());
		System.out.print(getEyt());
		System.out.print(getJzlcpx());
		System.out.print(getMet());
		System.out.print(getGsrkp());
		System.out.print(getCnpwue());
		System.out.print(getYvbc());
		System.out.print(getNojq());
		System.out.print((char) getXqcv());
		System.out.print(getVvk());
		System.out.print(getSeyz());
		System.out.print(getFssd());
		System.out.print((char) getPbfilj());
		System.out.print(getTvsm());
		System.out.print(getPfdihb());
		System.out.print(getFplcf());
		System.out.print(getNxsxj());
		System.out.print((char) getLdy());
		System.out.print(getOiwuru());
		System.out.print((char) getJhida());
		System.out.print(getDoi());
		System.out.print((char) getJnqx());
		System.out.print(getPrqkq());
		System.out.print(getPiiffw());
		System.out.print(getIhmqyu());
		System.out.print(getHyouh());
		System.out.print(getVcmni());
		System.out.print((char) getYiay());
		System.out.print(getAlqhfwj());
		System.out.print(getWfaszks());
		System.out.print(getYtsh());
		System.out.print(getMujzo());
		System.out.print((char) getVghq());
		System.out.print((char) getGlmqtoz());
		System.out.print((char) getLlj());
		System.out.print((char) getTojlcjv());
		System.out.print(getAcs());
		System.out.print(getWimuc());
		System.out.print((char) getCcg());
		System.out.print(getIudgj());
		System.out.print((char) getYkmbhtm());
		System.out.print(getQllxgya());
		System.out.print(getRwypckg());
		System.out.print(getNxqoz());
		System.out.print((char) getIjwxe());
		System.out.print(getLsxrjnl());
		System.out.print(getMxlfgxi());
		System.out.print(getTjxeket());
		System.out.print(getPxk());
		System.out.print((char) getBwxrkp());
		System.out.print(getFfy());
		System.out.print(getBdmv());
		System.out.print((char) getDyv());
		System.out.print((char) getYrgz());
		System.out.print((char) getJuucw());
		System.out.print((char) getSoi());
		System.out.print(getAmcrjl());
		System.out.print((char) getJrupss());
		System.out.print(getFtjgyoe());
		System.out.print(getWvz());
		System.out.print(getHrpetpa());
		System.out.print(getSepqtt());
		System.out.print((char) getBhtae());
		System.out.print(getIphll());
		System.out.print((char) getIzepreo());
		System.out.print(getJof());
		System.out.print((char) getSyjnriu());
		System.out.print(getBrj());
		System.out.print(getMxwek());
		System.out.print(getGscolo());
		System.out.print(getSfhurts());
		System.out.print(getKqn());
		System.out.print(getCodhwcw());
		System.out.print(getFuonzyd());
		System.out.print(getDzzjjz());
		System.out.print((char) getRzfkawh());
		System.out.print(getZxjvt());
		System.out.print(getZhgt());
		System.out.print((char) getLiyzdgx());
		System.out.print(getNxeyeq());
		System.out.print(getUhwpqee());
		System.out.print(getIhqdj());
		System.out.print((char) getXfyd());
		System.out.print(getUpg());
		System.out.print(getBcxrnch());
		System.out.print((char) getLoeq());
		System.out.print(getKvtn());
		System.out.print(getSwdc());
		System.out.print(getAxwb());
		System.out.print(getCgnm());
		System.out.print(getRev());
		System.out.print(getOahx());
		System.out.print(getWksfxf());
		System.out.print((char) getPylwybh());
		System.out.print(getJjetspl());
		System.out.print(getKewv());
		System.out.print((char) getJzsekyr());
		System.out.print(getUycct());
		System.out.print((char) getYlecwr());
		System.out.print(getAuua());
		System.out.print(getSilmzzz());
		System.out.print(getTadjpq());
		System.out.print((char) getWkdux());
		System.out.print((char) getBjjoi());
		System.out.print(getBakf());
		System.out.print(getRwxl());
		System.out.print(getJmeek());
		System.out.print(getQjf());
		System.out.print(getGfmlbyd());
		System.out.print((char) getLwy());
		System.out.print((char) getLtgwitm());
		System.out.print(getTlwvqa());
		System.out.print((char) getWakjfea());
		System.out.print((char) getIali());
		System.out.print((char) getWhkpycw());
		System.out.print(getBeedcl());
		System.out.print(getKcgmlr());
		System.out.print(getCjxpizx());
		System.out.print((char) getTdz());
		System.out.print((char) getKabqoil());
		System.out.print(getMeu());
		System.out.print((char) getUgbvlqh());
		System.out.print((char) getPvrb());
		System.out.print(getLxzksia());
		System.out.print((char) getPyt());
		System.out.print(getGeqoobb());
		System.out.print(getXpnnq());
		System.out.print((char) getAempf());
		System.out.print(getTylhp());
		System.out.print(getKsn());
		System.out.print(getOfhlzs());
		System.out.print(getHjn());
		System.out.print((char) getWdauz());
		System.out.print((char) getDhcavev());
		System.out.print((char) getFlkdwxe());
		System.out.print(getQagny());
		System.out.print(getLenw());
		System.out.print(getHkd());
		System.out.print((char) getObp());
		System.out.print(getQzofk());
		System.out.print((char) getVszi());
		System.out.print((char) getOmikz());
		System.out.print((char) getUifir());
		System.out.print(getYkmlx());
		System.out.print(getEojowu());
		System.out.print(getWcn());
		System.out.print(getIse());
		System.out.print(getHfemn());
		System.out.print((char) getImwbb());
		System.out.print(getQnptb());
		System.out.print((char) getPbm());
		System.out.print(getUjz());
		System.out.print(getGuo());
		System.out.print(getNktlg());
		System.out.print((char) getJujffwk());
		System.out.print(getFxcju());
		System.out.print((char) getOqfuapg());
		System.out.print(getKkcqz());
		System.out.print(getFyqr());
		System.out.print(getYuiq());
		System.out.print(getBaiyn());
		System.out.print(getMhpnfko());
		System.out.print(getGnftt());
		System.out.print(getXrmtoy());
		System.out.print((char) getQxptl());
		System.out.print(getNxwafq());
		System.out.print((char) getBhn());
		System.out.print(getQpeumpy());
		System.out.print(getLdflua());
		System.out.print((char) getXbn());
		System.out.print(getHqg());
		System.out.print(getQnmtuw());
		System.out.print(getEhv());
		System.out.print(getJmo());
		System.out.print(getCtf());
		System.out.print(getBfii());
		System.out.print((char) getYsclux());
		System.out.print(getBjttyqj());
		System.out.print(getSkazad());
		System.out.print(getXlvohq());
		System.out.print(getBbbbr());
		System.out.print((char) getRpnrebs());
		System.out.print((char) getNevutm());
		System.out.print(getKtuyfg());
		System.out.print(getPxn());
		System.out.print(getMjdgxi());
		System.out.print(getTdh());
		System.out.print(getNnwz());
		System.out.print(getGfcropb());
		System.out.print(getBjxl());
		System.out.print((char) getRsnno());
		System.out.print((char) getRgad());
		System.out.print(getQgo());
		System.out.print(getLcou());
		System.out.print((char) getGdia());
		System.out.print(getUslsgx());
		System.out.print(getIebite());
		System.out.print(getZzsqh());
		System.out.print((char) getLaesz());
		System.out.print(getXbdy());
		System.out.print((char) getGuijog());
		System.out.print(getVwzvnzd());
		System.out.print(getIlezg());
		System.out.print(getXdgmff());
		System.out.print(getDyvvmbi());
		System.out.print(getUhm());
		System.out.print(getZkwac());
		System.out.print((char) getAbuvco());
		System.out.print(getPmj());
		System.out.print(getNdsigx());
		System.out.print((char) getHzfi());
		System.out.print(getRmrzgwm());
		System.out.print(getGdp());
		System.out.print(getRmyzqhe());
		System.out.print((char) getUnppe());
		System.out.print(getVwxa());
		System.out.print(getPmf());
		System.out.print(getUhwut());
		System.out.print(getOihqfv());
		System.out.print(getXsffsa());
		System.out.print(getOzah());
		System.out.print(getPngbe());
		System.out.print((char) getWek());
		System.out.print((char) getAjw());
		System.out.print(getAzpfjvf());
		System.out.print(getDgeozqa());
		System.out.print(getLxxyfk());
		System.out.print((char) getFyypxzm());
		System.out.print(getKud());
		System.out.print((char) getGhdtgk());
		System.out.print(getYgfjv());
		System.out.print((char) getOxmuoq());
		System.out.print(getXav());
		System.out.print(getVnv());
		System.out.print((char) getPqckimr());
		System.out.print(getZooheih());
		System.out.print(getWlmkbm());
		System.out.print(getMds());
		System.out.print(getHiqb());
		System.out.print(getWiqkdkp());
		System.out.print(getNjaiv());
		System.out.print((char) getNlvd());
		System.out.print(getBbnajd());
		System.out.print((char) getZerlocv());
		System.out.print((char) getDtnx());
		System.out.print(getAiqkoy());
		System.out.print(getJwsircp());
		System.out.print((char) getFebvp());
		System.out.print(getLmw());
		System.out.print(getIyxuc());
		System.out.print(getRxnx());
		System.out.print((char) getUydb());
		System.out.print(getWmq());
		System.out.print(getVybh());
		System.out.print((char) getTha());
		System.out.print(getJscanj());
		System.out.print(getKheduwl());
		System.out.print(getAkve());
		System.out.print(getMzffm());
		System.out.print(getEkklbo());
		System.out.print(getFmttyn());
		System.out.print((char) getZsvzg());
		System.out.print(getAforsg());
		System.out.print(getCpeu());
		System.out.print(getXkn());
		System.out.print((char) getLwzlmp());
		System.out.print((char) getZrepsdn());
		System.out.print(getAjx());
		System.out.print(getFrp());
		System.out.print(getAqk());
		System.out.print(getDwc());
		System.out.print((char) getWcivk());
		System.out.print(getRqn());
		System.out.print(getFmiz());
		System.out.print(getCwa());
		System.out.print(getZnnhwk());
		System.out.print(getVwz());
		System.out.print(getHenosbb());
		System.out.print(getLrc());
		System.out.print(getCbtiu());
		System.out.print(getQcrda());
		System.out.print(getUqygpra());
		System.out.print(getFbtmqg());
		System.out.print(getRplbfu());
		System.out.print(getMcrhwil());
		System.out.print((char) getEmsnn());
		System.out.print(getHzgr());
		System.out.print(getDgyd());
		System.out.print(getRdz());
		System.out.print((char) getBdkz());
		System.out.print(getAjwvyqd());
		System.out.print(getTqhke());
		System.out.print(getNvsocn());
		System.out.print((char) getYkh());
		System.out.print(getZbzunpq());
		System.out.print((char) getYnnul());
		System.out.print(getEitn());
		System.out.print((char) getNfc());
		System.out.print((char) getDla());
		System.out.print((char) getHrsmw());
		System.out.print(getOisacku());
		System.out.print((char) getJednr());
		System.out.print(getDajpfb());
		System.out.print(getMtjay());
		System.out.print(getFwtlk());
		System.out.print((char) getOrfdcs());
		System.out.print(getDjqwy());
		System.out.print(getLmv());
		System.out.print((char) getMvqs());
		System.out.print((char) getMwi());
		System.out.print(getBxsvd());
		System.out.print(getPop());
		System.out.print(getLcvvltn());
		System.out.print((char) getQia());
		System.out.print(getQsgbj());
		System.out.print(getNdw());
		System.out.print(getSghbro());
		System.out.print(getYqy());
		System.out.print(getXuzc());
		System.out.print(getZugax());
		System.out.print(getHjro());
		System.out.print(getQmnbg());
		System.out.print((char) getEpouq());
		System.out.print(getPhztnka());
		System.out.print((char) getVjrlkx());
		System.out.print(getQfdt());
		System.out.print(getMeoby());
		System.out.print(getSimyp());
		System.out.print((char) getGknmphy());
		System.out.print(getQttckyf());
		System.out.print(getLcndnb());
		System.out.print(getNppvgu());
		System.out.print(getBxypkf());
		System.out.print(getZpyhra());
		System.out.print(getEblvg());
		System.out.print(getMskviqw());
		System.out.print(getKzhuy());
		System.out.print(getQblx());
		System.out.print(getNnhpoj());
		System.out.print(getNkx());
		System.out.print(getVirlxx());
		System.out.print(getCxxtoh());
		System.out.print(getKsuvr());
		System.out.print(getSys());
		System.out.print(getEmgykt());
		System.out.print(getShbnsdp());
		System.out.print(getVgry());
		System.out.print(getAvxpi());
		System.out.print(getZadyv());
		System.out.print(getDnuw());
		System.out.print((char) getNivxaxx());
		System.out.print(getAilx());
		System.out.print((char) getOajm());
		System.out.print((char) getLga());
		System.out.print(getHqtuki());
		System.out.print((char) getFiairh());
		System.out.print(getVad());
		System.out.print(getKcool());
		System.out.print((char) getVgl());
		System.out.print(getRgfx());
		System.out.print((char) getEnp());
		System.out.print(getYgrrlh());
		System.out.print(getXsode());
		System.out.print((char) getNjorhb());
		System.out.print(getAvzpf());
		System.out.print(getFbcgz());
		System.out.print(getUxrvi());
		System.out.print(getNqxhrb());
		System.out.print(getUwfzht());
		System.out.print(getCvgu());
		System.out.print(getCkwwjp());
		System.out.print(getWxa());
		System.out.print((char) getZscp());
		System.out.print(getOfkiso());
		System.out.print((char) getMix());
		System.out.print(getHlw());
		System.out.print(getYqoibvu());
		System.out.print(getNjk());
		System.out.print(getHioo());
		System.out.print(getGhix());
		System.out.print((char) getHau());
		System.out.print((char) getUgnj());
		System.out.print(getLxnm());
		System.out.print((char) getYtr());
		System.out.print(getCeewsse());
		System.out.print((char) getHqlv());
		System.out.print(getCzy());
		System.out.print(getMvsmqx());
		System.out.print(getOxdcdo());
		System.out.print(getAokutgd());
		System.out.print(getTiil());
		System.out.print(getImhpmpv());
		System.out.print((char) getAefpg());
		System.out.print(getRwngd());
		System.out.print(getGpndsp());
		System.out.print(getBzxbtw());
		System.out.print(getZoti());
		System.out.print(getOsk());
		System.out.print(getHzuamd());
		System.out.print(getUmzvhs());
		System.out.print((char) getTdkdnkn());
		System.out.print((char) getFgkk());
		System.out.print((char) getTfym());
		System.out.print(getHnowfda());
		System.out.print((char) getDdjii());
		System.out.print(getOiaw());
		System.out.print(getAjmzpq());
		System.out.print(getQtan());
		System.out.print(getJupym());
		System.out.print((char) getVrj());
		System.out.print(getTcxeo());
		System.out.print(getBwvnz());
	}

	private void set() {
		setTalu("\u2580");
		setFebvp(9618);
		setYsclux(9600);
		setHqlv(9617);
		setKqaq("\u2584");
		setMix(9604);
		setJzlcpx('\u2591');
		setMxwek('\u2584');
		setFlkdwxe(9617);
		setDyvvmbi('\u2592');
		setOwlt("\u2591");
		setAokutgd('\u2591');
		setAjwvyqd('\u2591');
		setLtoxdz(9617);
		setFox('\u2591');
		setToh("\u2584");
		setLga(9617);
		setWek(9617);
		setYrgz(9617);
		setIyogpx("\u2584");
		setMskviqw('\u2592');
		setIse('\u2584');
		setYqoibvu("\u2591");
		setDhcavev(9617);
		setQnptb("\u2588");
		setMzffm('\u2592');
		setZnnhwk("\u2592");
		setJbkqa(9618);
		setNdw("\u2592");
		setDshkwx(9618);
		setCbtiu('\u2592');
		setThic(9618);
		setGbtijos(9600);
		setQmnbg("\n");
		setDnjc("\u2590");
		setXav("\u2591");
		setYkmlx('\u2592');
		setLaesz(9618);
		setJgcmo(9617);
		setDyv(9617);
		setGknmphy(9618);
		setRmyzqhe('\u2584');
		setFtjgyoe('\u2588');
		setXlahlar("\u2592");
		setOihqfv('\u2592');
		setCgnm('\u2592');
		setUuzhq(9617);
		setMhsyar('\u2591');
		setMomcef('\u2580');
		setHgtjnfj("\u2591");
		setQzofk("\u258c");
		setQhds('\u2591');
		setMij("\u2591");
		setAxwb('\u2592');
		setGfcropb("\u2592");
		setZrepsdn(9618);
		setMvsmqx('\u2591');
		setDtnx(9618);
		setUqygpra("\u2592");
		setUhm('\u2592');
		setRwxl("\u2592");
		setIlezg('\u2590');
		setVtnhtan(9617);
		setKcgmlr("\u2584");
		setOnull('\u2592');
		setAqrf(9604);
		setQgvxa('\u2592');
		setOxdcdo('\u2591');
		setNivqumq(9618);
		setAforsg('\u2591');
		setOqfuapg(9617);
		setMdh('\u2592');
		setWksfxf('\u2592');
		setQxacpne("\u2591");
		setShbnsdp('\u2592');
		setAefpg(9618);
		setTadjpq("\u2591");
		setObp(9618);
		setOwxhn("\u2591");
		setThs("\u2591");
		setHrsmw(9618);
		setBcxrnch("\u2591");
		setTfym(9600);
		setMcrhwil("\u2592");
		setHfemn("\u2588");
		setRovwopz("\u2591");
		setNfc(9618);
		setOfkiso("\u2584");
		setFgkk(9600);
		setNkx('\u2584');
		setIyxuc('\u2591');
		setBqounh("\u2591");
		setBjttyqj('\u2590');
		setWsr('\u2591');
		setPiiffw('\u2591');
		setSkazad("\u2580");
		setRpkacz(9617);
		setQllxgya("\u2592");
		setZhgt('\u2592');
		setAjx("\u2592");
		setEitn('\u2592');
		setJtaqm(9600);
		setXbdy('\u2592');
		setGuo("\u2591");
		setUgnj(10);
		setUslsgx('\u2591');
		setOisacku('\u2592');
		setBwvnz('\n');
		setAilx('\n');
		setOcfifg(9600);
		setAnqas("\u2591");
		setMvqs(9618);
		setZgkvkwc("\u2590");
		setRmrzgwm("\u2592");
		setTylhp("\u2592");
		setMxlfgxi('\u2592');
		setHiqb("\u2592");
		setPop("\u2591");
		setFmttyn("\u2591");
		setBunnx(9618);
		setHzbtjm('\u2591');
		setPvg(9617);
		setDlwb("\u2591");
		setUgbvlqh(9618);
		setMtjay('\u2592');
		setKud("\u2592");
		setMeoby('\u2580');
		setKfz('\u2591');
		setBrj('\u2588');
		setJzsekyr(9608);
		setVghq(9618);
		setCxxtoh('\u2580');
		setJarvuxd("\u2591");
		setWalxxz(9617);
		setJof('\u2584');
		setPxty("\u2592");
		setYhhklch(9617);
		setAfpdhe('\u2592');
		setLnstq(9617);
		setEkklbo("\u258c");
		setTdkdnkn(9618);
		setLcvvltn("\u2592");
		setSfhurts("\u2592");
		setYtr(9617);
		setKewv('\u258c');
		setQcrda("\u2591");
		setRqn('\u2592');
		setXrmtoy("\u2591");
		setAkve('\u2592');
		setUxrvi("\u2580");
		setVwzvnzd('\n');
		setTdz(9608);
		setZoti('\u2592');
		setLdy(9612);
		setImwbb(9604);
		setEojowu("\u2580");
		setHlw('\u2580');
		setPpijfvs('\u2591');
		setUmzvhs("\u2592");
		setGnftt('\u2591');
		setOzah("\u2592");
		setQia(9604);
		setDwc("\u2592");
		setVwz('\u2592');
		setGqj('\u2591');
		setKabqoil(9604);
		setQsgbj("\u2592");
		setMwi(9617);
		setCpeu("\u2590");
		setWmvyyd(9617);
		setOmzs("\u2590");
		setNlvd(9600);
		setQnsf(9617);
		setOsk("\u2592");
		setUhwut("\u2592");
		setNdsigx("\u2584");
		setFuonzyd('\u2592');
		setPfdihb('\u2588');
		setWimuc("\u2592");
		setNxeyeq('\u2591');
		setQodrweo("\u2591");
		setHqg('\u2591');
		setCyjzpx('\u2591');
		setYiay(9618);
		setBakf("\u2592");
		setLkqrh("\u2591");
		setUnppe(9618);
		setJrupss(9612);
		setJjyvon(9617);
		setAzpfjvf('\u2591');
		setXfyd(9617);
		setTjxeket('\u2592');
		setHyouh('\u2592');
		setOiaw("\u2591");
		setEhv('\u2590');
		setNxqoz('\u2592');
		setAvzpf("\u2584");
		setIzepreo(9618);
		setEblvg("\u2592");
		setWxa("\u2592");
		setVnv("\u258c");
		setKvtn("\u2591");
		setWbfajfn("\u2584");
		setOxmuoq(10);
		setDowi('\u2591');
		setXkn("\u2592");
		setNxwafq('\u2591');
		setDoi('\u2591');
		setGyznywk("\n");
		setGfj(9617);
		setOfhlzs('\u2591');
		setBhn(9618);
		setQgo("\u2592");
		setZooheih("\u2592");
		setVirlxx('\u2584');
		setZjjag('\u2591');
		setXqdwdg('\u2591');
		setCpf(9617);
		setYqy("\u2592");
		setCiefn('\u2592');
		setBdmv('\n');
		setNivxaxx(9617);
		setPyt(9618);
		setZwlsist(9617);
		setVmkyv(9617);
		setNjaiv("\u2580");
		setRgad(9617);
		setLcndnb("\u2592");
		setAtm(9617);
		setSoi(9617);
		setHjn("\u2591");
		setNqxhrb('\u2580');
		setHioo("\u2591");
		setNjk("\u2591");
		setEwjevks(9617);
		setKcool('\u2591');
		setAempf(9618);
		setScinylp("\u2591");
		setIebite('\u2592');
		setRnn(9617);
		setJhida(9617);
		setKkcqz("\u2591");
		setBduanf("\u2584");
		setAcs('\u2591');
		setWvz('\u2580');
		setPhztnka("\u2591");
		setVrj(9617);
		setNdkpjbn(9617);
		setLmv("\u2591");
		setSys('\u2592');
		setWzxcqy(10);
		setTfr('\u2584');
		setLrc("\u2591");
		setGfmlbyd("\u2584");
		setAqk('\u2592');
		setPrqkq("\u2591");
		setVajcgb('\u2591');
		setYkrvop('\u2584');
		setWpnaokk("\u2591");
		setDgyd('\u2592');
		setCvgu('\u2592');
		setUifir(9600);
		setBbnajd('\u2580');
		setZzsqh("\u2592");
		setPoz(9617);
		setLxfn('\u2592');
		setXuzc("\u258c");
		setBeedcl("\u2592");
		setVcmni('\u2592');
		setPnmpunm('\u2591');
		setKvyjhuh(9612);
		setHbac(9604);
		setYtsh('\u2592');
		setNgyfc(9617);
		setAiqkoy("\u2592");
		setRgfx('\u2584');
		setLenw("\u2592");
		setRwngd("\u2592");
		setVgl(9600);
		setWakjfea(9617);
		setWfaszks('\u2584');
		setZrkhllh("\u2592");
		setRsnno(9618);
		setMhpnfko('\u2591');
		setZugax('\u2591');
		setQjrvip('\u2591');
		setQtan('\u2591');
		setFwtlk("\u2592");
		setYgbcck("\u2591");
		setAlqhfwj("\u2584");
		setMjdgxi('\u2592');
		setNnhpoj("\u2584");
		setBbbbr('\u2591');
		setJwsircp('\u2592');
		setQblx("\u2592");
		setYgrrlh("\u2584");
		setZadyv('\u2591');
		setYgfjv("\u2591");
		setBxypkf('\u2592');
		setZbzunpq("\u2580");
		setHrpetpa('\u2592');
		setRwypckg('\u2592');
		setFfy("\u2591");
		setFplcf('\u2580');
		setZmspifu(9618);
		setBwxrkp(9617);
		setArobm("\u2591");
		setFiairh(9617);
		setDgeozqa("\u2592");
		setGnigv('\u2588');
		setNfo('\u2592');
		setVvk('\u2592');
		setPqckimr(9618);
		setTqhke("\n");
		setBxsvd('\u2592');
		setJednr(9618);
		setSycao(9618);
		setAjw(9618);
		setDnuw("\u2591");
		setUpg("\u2590");
		setHjro('\u2591');
		setRpnrebs(9604);
		setUjz("\u2584");
		setZipzga("\u2591");
		setCua('\n');
		setGdp('\u2592');
		setBkus(9600);
		setFhuk(9618);
		setVgry("\u2584");
		setYrp('\n');
		setJjetspl("\u2592");
		setBeqyn('\u2591');
		setLwzlmp(9618);
		setDhfj("\u2591");
		setEdtugo(9617);
		setBjjoi(9617);
		setIya(9617);
		setZscp(9618);
		setKsuvr('\u2592');
		setRdz('\u2590');
		setGdia(9618);
		setNktlg("\u2580");
		setBaiyn('\u2591');
		setVad("\u2591");
		setQttckyf('\u2592');
		setVke("\u2591");
		setOahx("\u2592");
		setSqb('\u2591');
		setIuhxktq(9617);
		setYkh(9617);
		setCkwwjp("\u2592");
		setHzuamd('\u2592');
		setVjrlkx(9617);
		setDzzjjz('\u2592');
		setEnp(9604);
		setYwtp(9617);
		setHasc('\u2591');
		setPgjwz('\u2591');
		setYlecwr(9600);
		setXqcv(9617);
		setLmw("\u2592");
		setJmo("\u2592");
		setNxsxj('\u2592');
		setAuua('\u2592');
		setHau(9617);
		setBzgx("\u2592");
		setAmcrjl('\u2591');
		setNojq("\u2591");
		setVjvlz("\u2591");
		setEprrnfy("\u2584");
		setJea(9617);
		setEmelqya('\u2591');
		setSepqtt("\u2592");
		setLxzksia('\u2592');
		setOmpefy('\u2591');
		setXsode("\u2584");
		setIzk('\u2592');
		setImhpmpv("\u2592");
		setPmf("\u2592");
		setWdauz(9617);
		setIudgj('\u2592');
		setDst(10);
		setUycct('\u2588');
		setSwdc("\u2592");
		setXdgmff('\u2592');
		setCcg(9618);
		setZpyhra("\u2592");
		setZkwac('\u2580');
		setWkdux(9617);
		setWmq('\u2592');
		setHnowfda('\u2591');
		setCtf('\u2592');
		setDla(9618);
		setLwy(9612);
		setLxxyfk("\u2591");
		setWcn('\u2590');
		setVybh("\u2591");
		setPmj('\u2584');
		setUydb(9617);
		setPno('\u2591');
		setNvsocn("\u2591");
		setOrmctb('\u258c');
		setTucxhh('\u2588');
		setGhdtgk(9616);
		setJqnd(9600);
		setJuucw(9612);
		setIxfr("\u2591");
		setFbcgz("\u2580");
		setBfii("\u2590");
		setRiklilh(9617);
		setYnnul(9604);
		setSeyz("\u2592");
		setNnwz("\u2592");
		setHbibpn(9618);
		setNppvgu("\u2592");
		setFssd("\u2592");
		setTdh("\u2592");
		setDajpfb("\u2592");
		setLdflua("\u2592");
		setHzfi(9618);
		setLxnm('\u2591');
		setGsrkp('\u2592');
		setSimyp("\u2584");
		setMet('\u2592');
		setNevutm(9604);
		setIphll('\u2592');
		setJupym("\u2591");
		setIhqdj('\n');
		setTojlcjv(9617);
		setPngbe('\u2592');
		setPxk("\u258c");
		setTiil('\u2591');
		setZsvzg(10);
		setKwzh("\u2591");
		setWiqkdkp("\u2592");
		setIoocj(9617);
		setVwxa("\u2592");
		setQfdt('\u2591');
		setTlwvqa('\n');
		setHqtuki('\u2591');
		setAolxpal('\u2591');
		setMeu('\u2592');
		setTha(9618);
		setIhmqyu("\u2590");
		setUmoki(9617);
		setLcou("\u2591");
		setXaqq(9617);
		setEpouq(9617);
		setZdn(9600);
		setOrfdcs(9618);
		setFbtmqg("\u2591");
		setSoqri('\u2592');
		setSyjnriu(9600);
		setCjl("\u2591");
		setKqdevv('\u2584');
		setPmmfl("\u2591");
		setRzfkawh(9618);
		setAdhx(9618);
		setMds("\u2592");
		setEyt("\u2591");
		setGhix("\u2591");
		setEmgykt("\u2592");
		setQjf('\u2580');
		setUtdquob(9617);
		setQxptl(9617);
		setGuijog(9612);
		setFyypxzm(9618);
		setUznm(9618);
		setGlmqtoz(9618);
		setKsn('\u2591');
		setLiyzdgx(9616);
		setXbn(9616);
		setSwq(9618);
		setZerlocv(9618);
		setMujzo('\u2592');
		setOajm(9617);
		setLileqj("\u258c");
		setFrp("\u2592");
		setPxn('\u2584');
		setDjqwy("\u2592");
		setGscolo('\u2592');
		setYkmbhtm(9618);
		setXpnnq("\u2592");
		setTcxeo("\u2591");
		setFxcju('\u2592');
		setCwa("\u2592");
		setPvrb(9618);
		setCjxpizx('\u2588');
		setUhwpqee('\u2591');
		setKtuyfg('\u2592');
		setXsffsa('\u2592');
		setCodhwcw("\u2592");
		setJnqx(10);
		setIali(9612);
		setPbm(9612);
		setSzfcxq('\u2592');
		setQnmtuw("\n");
		setHzgr("\u2592");
		setWuwibie('\u2591');
		setCvtddim(9600);
		setSilmzzz("\u2592");
		setCehyni('\u2591');
		setKzhuy("\u2592");
		setPylwybh(9618);
		setNcsbxv("\u2592");
		setLsxrjnl('\u2584');
		setCubs(9618);
		setOmikz(10);
		setBjxl('\u2592');
		setLlj(9617);
		setZxjvt("\u2588");
		setKheduwl('\u2592');
		setJmeek('\u2592');
		setSghbro("\u2592");
		setFmiz('\u2592');
		setBdkz(9617);
		setCeewsse('\u2591');
		setKzbldk('\u2591');
		setXcqkxd("\u2580");
		setJujffwk(9618);
		setAjmzpq("\u2591");
		setGeqoobb('\u2592');
		setEmsnn(9604);
		setOiwuru("\u2591");
		setVszi(9617);
		setTvsm("\u2588");
		setLhjxtbb('\u2591');
		setAbuvco(9600);
		setGpndsp('\u2592');
		setKmrkc('\u2584');
		setNjorhb(9604);
		setYuiq('\u2591');
		setBzxbtw('\u2592');
		setLpgj(9617);
		setLnwm('\u2588');
		setCzy("\u2591");
		setDfu('\u2591');
		setKqn("\u2592");
		setCbililv(9617);
		setGzu('\u2590');
		setBhtae(9618);
		setXlvohq("\u2592");
		setLkzg("\u2592");
		setLoeq(9617);
		setJscanj('\u2591');
		setIjwxe(9600);
		setAvxpi('\u2580');
		setYvbc("\u2591");
		setWhkpycw(9617);
		setHkd("\u2592");
		setQlejrpb('\u2591');
		setHenosbb('\u2592');
		setRev("\u2592");
		setPbfilj(9600);
		setRplbfu('\u2592');
		setQagny('\u2592');
		setDdjii(9617);
		setRxnx("\u2592");
		setWcivk(9618);
		setUwfzht("\u2592");
		setWlmkbm('\u2592');
		setQpeumpy('\u2592');
		setUfax("\u2591");
		setCnpwue("\u2592");
		setLtgwitm(9617);
		setFyqr("\u2591");
		setNba("\u2588");
		setWky(9617);
		setFun('\u2592');
		setNddgs('\u2591');
	}

	private String nktlg;
	private char bbnajd;
	private int hbac;
	private String zbzunpq;
	private int tdkdnkn;
	private char wlmkbm;
	private String ihmqyu;
	private char xqdwdg;
	private String pxty;
	private int tfym;
	private char fuonzyd;
	private char wcn;
	private int izepreo;
	private String qnptb;
	private String vgry;
	private char wsr;
	private char cua;
	private int walxxz;
	private char qtan;
	private char wvz;
	private char ceewsse;
	private String ofkiso;
	private String gfmlbyd;
	private String emgykt;
	private String ajmzpq;
	private char met;
	private int rgad;
	private int zscp;
	private int soi;
	private char ompefy;
	private int hbibpn;
	private char gsrkp;
	private char azpfjvf;
	private int dhcavev;
	private char ailx;
	private String zzsqh;
	private char lxnm;
	private char qlejrpb;
	private String ckwwjp;
	private char ormctb;
	private int rzfkawh;
	private String nvsocn;
	private String anqas;
	private int pqckimr;
	private int wakjfea;
	private String simyp;
	private int pyt;
	private String vjvlz;
	private int ijwxe;
	private String sepqtt;
	private char tjxeket;
	private String ygfjv;
	private int thic;
	private int dst;
	private char gzu;
	private int ocfifg;
	private int yrgz;
	private int ghdtgk;
	private String vwxa;
	private String xrmtoy;
	private int hzfi;
	private char axwb;
	private int cvtddim;
	private char ksn;
	private int ysclux;
	private int lwzlmp;
	private char wksfxf;
	private int uuzhq;
	private int vghq;
	private int pylwybh;
	private String lcndnb;
	private String rovwopz;
	private int whkpycw;
	private char sys;
	private int utdquob;
	private int bhn;
	private String hzgr;
	private char pxn;
	private char bdmv;
	private char meu;
	private int nivxaxx;
	private char iudgj;
	private String mds;
	private char jof;
	private char hjro;
	private int wcivk;
	private int dshkwx;
	private String nppvgu;
	private int ccg;
	private char rqn;
	private char uycct;
	private char uhwpqee;
	private int kvyjhuh;
	private int jujffwk;
	private int bunnx;
	private int ewjevks;
	private String kud;
	private char nxqoz;
	private int lnstq;
	private int loeq;
	private int flkdwxe;
	private String skazad;
	private char pfdihb;
	private char oihqfv;
	private String nba;
	private char kfz;
	private int fyypxzm;
	private int ajw;
	private String uxrvi;
	private char ise;
	private int wky;
	private char momcef;
	private char afpdhe;
	private String osk;
	private char baiyn;
	private int vszi;
	private char vwzvnzd;
	private char virlxx;
	private int ltoxdz;
	private char cbtiu;
	private int pvrb;
	private String lenw;
	private int laesz;
	private int aefpg;
	private String dnuw;
	private int qxptl;
	private int ykmbhtm;
	private int kabqoil;
	private int liyzdgx;
	private int riklilh;
	private char jscanj;
	private int pbm;
	private String fyqr;
	private int dtnx;
	private char pmj;
	private char mskviqw;
	private String qgo;
	private char ehv;
	private char bjttyqj;
	private char lnwm;
	private String lcou;
	private String sfhurts;
	private int umoki;
	private int iya;
	private int ylecwr;
	private char ppijfvs;
	private String yqy;
	private char hasc;
	private String nnhpoj;
	private int adhx;
	private String qxacpne;
	private char nddgs;
	private char fun;
	private char ctf;
	private String lkqrh;
	private int jnqx;
	private String oiwuru;
	private char xsffsa;
	private String tcxeo;
	private String lileqj;
	private String fssd;
	private int vmkyv;
	private char akve;
	private int jbkqa;
	private int oxmuoq;
	private char geqoobb;
	private int vtnhtan;
	private String lrc;
	private char mujzo;
	private String hjn;
	private char acs;
	private char cjxpizx;
	private int oqfuapg;
	private String rev;
	private String mij;
	private String swdc;
	private String hkd;
	private char mjdgxi;
	private char lhjxtbb;
	private String ncsbxv;
	private String wbfajfn;
	private String njk;
	private char tiil;
	private String prqkq;
	private String tadjpq;
	private String xcqkxd;
	private char doi;
	private int lwy;
	private String oahx;
	private int pbfilj;
	private int wzxcqy;
	private char bbbbr;
	private char qttckyf;
	private String fbtmqg;
	private char fox;
	private char nkx;
	private char uhm;
	private String ufax;
	private String guo;
	private int mvqs;
	private char mxlfgxi;
	private int rpkacz;
	private char cvgu;
	private char jzlcpx;
	private char bwvnz;
	private char hlw;
	private String dwc;
	private String pmmfl;
	private char rplbfu;
	private int xbn;
	private char gqj;
	private String rxnx;
	private char mxwek;
	private String aiqkoy;
	private char meoby;
	private int fgkk;
	private int gdia;
	private char izk;
	private int wek;
	private char yrp;
	private String rwngd;
	private String xav;
	private int qnsf;
	private char mhpnfko;
	private char fplcf;
	private String cwa;
	private char rmyzqhe;
	private String ths;
	private int nevutm;
	private int tha;
	private int fiairh;
	private char yuiq;
	private String imhpmpv;
	private int zdn;
	private char rdz;
	private String lmw;
	private String vybh;
	private String rmrzgwm;
	private String bzgx;
	private int ngyfc;
	private char gnftt;
	private char gdp;
	private String oiaw;
	private String ekklbo;
	private String codhwcw;
	private char wuwibie;
	private char vajcgb;
	private String ldflua;
	private int dyv;
	private String xlvohq;
	private char ksuvr;
	private char jwsircp;
	private int nivqumq;
	private char soqri;
	private char zugax;
	private char ofhlzs;
	private char dzzjjz;
	private char beqyn;
	private String bfii;
	private String pxk;
	private char bzxbtw;
	private char sqb;
	private String cjl;
	private int gbtijos;
	private int njorhb;
	private char ihqdj;
	private String tqhke;
	private int bhtae;
	private String zrkhllh;
	private String gfcropb;
	private String mcrhwil;
	private int cbililv;
	private char vvk;
	private String lcvvltn;
	private String toh;
	private char jmeek;
	private String bduanf;
	private String qnmtuw;
	private int edtugo;
	private char cxxtoh;
	private String yqoibvu;
	private int ywtp;
	private char kcool;
	private char vwz;
	private String cpeu;
	private String lmv;
	private int ltgwitm;
	private char emelqya;
	private int cubs;
	private char vcmni;
	private char xdgmff;
	private char oisacku;
	private char ciefn;
	private char gscolo;
	private String ygrrlh;
	private String fmttyn;
	private String bakf;
	private String zipzga;
	private String rwxl;
	private int jednr;
	private String bcxrnch;
	private int mix;
	private int lpgj;
	private String nojq;
	private String cnpwue;
	private String zxjvt;
	private int vjrlkx;
	private String qblx;
	private char oxdcdo;
	private char hyouh;
	private char ykrvop;
	private String wiqkdkp;
	private char qfdt;
	private int sycao;
	private int xqcv;
	private char ilezg;
	private String kcgmlr;
	private String upg;
	private String phztnka;
	private String uwfzht;
	private String ujz;
	private char rwypckg;
	private String kvtn;
	private String ozah;
	private String vke;
	private String gyznywk;
	private char lxfn;
	private String dajpfb;
	private String kkcqz;
	private char kzbldk;
	private String xkn;
	private int ykh;
	private int cpf;
	private int xfyd;
	private String scinylp;
	private char tfr;
	private int uydb;
	private char iphll;
	private char cyjzpx;
	private char tlwvqa;
	private char rgfx;
	private char nxsxj;
	private String xlahlar;
	private String fbcgz;
	private String kqn;
	private String lkzg;
	private char mtjay;
	private int atm;
	private char zoti;
	private int pvg;
	private int swq;
	private int jzsekyr;
	private char iebite;
	private String qllxgya;
	private int guijog;
	private int emsnn;
	private String uhwut;
	private String jjetspl;
	private char zkwac;
	private char mvsmqx;
	private int uifir;
	private int enp;
	private char ajwvyqd;
	private String zpyhra;
	private char eitn;
	private int jjyvon;
	private char pngbe;
	private char dgyd;
	private int unppe;
	private String xpnnq;
	private int hqlv;
	private char uslsgx;
	private char kewv;
	private char mhsyar;
	private String ndsigx;
	private char dfu;
	private String umzvhs;
	private String owxhn;
	private char cgnm;
	private int bdkz;
	private int ytr;
	private int omikz;
	private char tucxhh;
	private char zhgt;
	private String hgtjnfj;
	private String frp;
	private char aokutgd;
	private String hiqb;
	private String vnv;
	private char onull;
	private String omzs;
	private String pop;
	private char pnmpunm;
	private String uqygpra;
	private int wdauz;
	private int jhida;
	private String iyogpx;
	private char piiffw;
	private String qsgbj;
	private char henosbb;
	private String avzpf;
	private char bxsvd;
	private char xbdy;
	private char auua;
	private char aqk;
	private String njaiv;
	private String fwtlk;
	private char qjrvip;
	private char mzffm;
	private String dgeozqa;
	private char nqxhrb;
	private String znnhwk;
	private int juucw;
	private String kwzh;
	private int gfj;
	private int hau;
	private String arobm;
	private int fhuk;
	private int qia;
	private String owlt;
	private char kqdevv;
	private int vgl;
	private String eyt;
	private String qmnbg;
	private int jgcmo;
	private char lsxrjnl;
	private int glmqtoz;
	private int zerlocv;
	private char amcrjl;
	private String hioo;
	private char kmrkc;
	private String ndw;
	private int iuhxktq;
	private char ktuyfg;
	private String eprrnfy;
	private int aempf;
	private String qcrda;
	private int dla;
	private char gpndsp;
	private int nlvd;
	private int xaqq;
	private int jtaqm;
	private String jupym;
	private char szfcxq;
	private int aqrf;
	private int rpnrebs;
	private char qagny;
	private String pmf;
	private char brj;
	private String yvbc;
	private char ftjgyoe;
	private String hfemn;
	private String jmo;
	private char shbnsdp;
	private String czy;
	private int ugnj;
	private int rsnno;
	private String qzofk;
	private int orfdcs;
	private int hrsmw;
	private String zgkvkwc;
	private int zsvzg;
	private String ixfr;
	private char mdh;
	private int ddjii;
	private int febvp;
	private String dhfj;
	private char nfo;
	private char ytsh;
	private char wfaszks;
	private char bjxl;
	private String tvsm;
	private char hqg;
	private char pgjwz;
	private char cehyni;
	private String qodrweo;
	private String zooheih;
	private String nnwz;
	private char dyvvmbi;
	private char zadyv;
	private String wpnaokk;
	private char hnowfda;
	private String eojowu;
	private String dnjc;
	private int llj;
	private char wmq;
	private String seyz;
	private int zwlsist;
	private String vad;
	private String wimuc;
	private int wkdux;
	private char qhds;
	private String tdh;
	private char aforsg;
	private int ldy;
	private int lga;
	private char gnigv;
	private char zjjag;
	private int vrj;
	private int mwi;
	private char kheduwl;
	private int gknmphy;
	private String sghbro;
	private char aolxpal;
	private int rnn;
	private int uznm;
	private char fxcju;
	private int tojlcjv;
	private int yiay;
	private int jrupss;
	private int oajm;
	private int jqnd;
	private String kzhuy;
	private String silmzzz;
	private int zrepsdn;
	private char dowi;
	private char qgvxa;
	private char qjf;
	private char nxwafq;
	private String dlwb;
	private String alqhfwj;
	private char lxzksia;
	private int nfc;
	private char hzbtjm;
	private String beedcl;
	private char avxpi;
	private char hqtuki;
	private int syjnriu;
	private String lxxyfk;
	private int ioocj;
	private char hrpetpa;
	private String tylhp;
	private String ygbcck;
	private int wmvyyd;
	private int bwxrkp;
	private String djqwy;
	private char pno;
	private char iyxuc;
	private int obp;
	private int imwbb;
	private int bkus;
	private String eblvg;
	private int iali;
	private String xsode;
	private char nxeyeq;
	private int tdz;
	private int ugbvlqh;
	private char qpeumpy;
	private char bxypkf;
	private String jarvuxd;
	private String bqounh;
	private char ykmlx;
	private int jea;
	private String ghix;
	private int ndkpjbn;
	private String talu;
	private String kqaq;
	private int zmspifu;
	private int yhhklch;
	private int epouq;
	private String ffy;
	private String xuzc;
	private int poz;
	private char fmiz;
	private char hzuamd;
	private int abuvco;
	private int bjjoi;
	private String ajx;
	private String wxa;
	private int ynnul;
}
